""" Список mqtt топиков для каждого модуля. Стандарт: mqtt_topic_<название модуля> """

list_of_mqtt_topics = [ ("/devices/HeaterModule/controls/MEAS DAC Vout", 0),
                        ("/devices/HeaterModule/controls/MEAS SW REG Vout", 0),
                        ("/devices/HeaterModule/controls/MEAS LDO REG Vout", 0),
                        ("/devices/HeaterModule/controls/MEAS Load Current", 0),
                        ("/devices/HeaterModule/controls/MEAS REG Vdelta", 0),
                        ("/devices/HeaterModule/controls/OverCrrent Status", 0),
                        ("/devices/HeaterModule/controls/Output Voltage State", 0),
                        ("/devices/MeasureModule/controls/CH1 Voltage", 0),
                        ("/devices/MeasureModule/controls/CH2 Voltage", 0),
                        ("/devices/MeasureModule/controls/CH1 Resistance", 0),
                        ("/devices/MeasureModule/controls/CH2 Resistance", 0),
                        ("/devices/FilteredValues/controls/CH1 Current", 0),
                        ("/devices/FilteredValues/controls/CH1 Temperature", 0),
                        ("/devices/FilteredValues/controls/CH2 Temperature", 0),
                        ("/devices/FilteredValues/controls/CH2 Current", 0),
                        ("/devices/FilteredValues/controls/LDO Power", 0),
                        ("/devices/FilteredValues/controls/LDO Voltage", 0),
                        ("/devices/MeasureModuleSetpoints/controls/CH1 State", 0),
                        ("/devices/MeasureModuleSetpoints/controls/CH2 State", 0)
                                 ]

mqtt_topics_pid = [("/devices/HeaterModule/controls/MEAS LDO REG Vout", 0),
                           ("/devices/HeaterModuleSetpoints/controls/LDO Voltage RampRate", 0),
                           ("/devices/HeaterModuleSetpoints/controls/LDO Voltage Setpoint", 0),
                           ("/devices/HeaterModuleSetpoints/controls/LDO Voltage MAX", 0),
                           ("/devices/MeasureModuleSetpoints/controls/PID Kp", 0),
                           ("/devices/MeasureModuleSetpoints/controls/PID Ki", 0),
                           ("/devices/MeasureModuleSetpoints/controls/PID Kd", 0),
                           ("/devices/HeaterModuleSetpoints/controls/LDO Current Setpoint", 0),
                           ("/devices/HeaterModuleSetpoints/controls/LDO Current MAX", 0),
                           ("/devices/MeasureModuleSetpoints/controls/Data Filter Type", 0),
                           ("/devices/MeasureModuleSetpoints/controls/Data Filter BufferSize", 0),
                           ("/devices/MeasureModuleSetpoints/controls/CH1 Current Setpoint", 0),
                           ("/devices/MeasureModuleSetpoints/controls/CH2 Current Setpoint", 0),
                           ("/devices/MeasureModuleSetpoints/controls/CH1 State", 0),
                           ("/devices/MeasureModuleSetpoints/controls/CH2 State", 0),
                           ("/devices/MeasureModule/controls/CH1 Current", 0),
                           ("/devices/MeasureModule/controls/CH2 Current", 0),
                           ("/devices/HeaterModule/controls/Output Voltage State", 0),
                           ("/devices/FilteredValues/controls/CH1 Temperature", 0),
                           ("/devices/MeasureModuleSetpoints/controls/CH1 Temperature Setpoint", 0),
                           ]